spring:
  application:
    name: java-springboot-api
  datasource:
    url: jdbc:mysql://localhost:3306/shopgolang
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  mail:
    port: 587
    host: smtp.gmail.com
    username: dangpham112000@gmail.com
    password:
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      group-id: otp-group-id
      enable-auto-commit: true