spring:
  application:
    name: java-springboot-api
  datasource:
    url: jdbc:mysql://localhost:3306/shopgolang
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
